### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by OceanOak**

### CODE REVIEW

**Review by pbiggar — CHANGES_REQUESTED** [review]
I don't quite follow what's going on here. Isn't fantomas version 5 these days? Or is this a dotnet wrapper for it?

**Comment by OceanOak** [comment]
> I don't quite follow what's going on here. Isn't fantomas version 5 these days? Or is this a dotnet wrapper for it?

I tried to use version 5.0.6 and it caused this error:
```
error NU1102: Unable to find package dotnet-fantomas with version (>= 5.0.6)
```
If I don't specify the version it will give me this warning:
```
 Project dependency dotnet-fantomas does not contain an inclusive lower bound
```

**Comment by OceanOak** [comment]
I found that dotnet-fantomas has been deprecated. The suggested alternative for it is fantomas.
Trying to figure out the proper way to use it since it doesn't use packageReference.

**Comment by pbiggar** [comment]
I'm trying to package tablecloth-fsharp and I'm redoing how we do packages, so I'll work this change into it. Thanks!

**Pull request closed without merging**
